### ISSUE TITLE
Create challenge homepage

### ISSUE THREAD

**Issue by joshpickard** [joshpickardme/frontend-mentor#11]
## Description
Create the homepage for the application which is a full directory of all the frontend mentor challenges that I have completed so far. The idea, is to get it looking as similar to the actual Frontend Mentor website as possible (maybe with a few creative changes).

## Tasks

- [x] Complete #3
- [x] Responsive grid layout
- [ ] Search (search correlates to name of challenge)
- [ ] Difficulty filter (to only show specific difficulties)
- [ ] Language filter (to only show specific languages)
